### ISSUE TITLE
Crashes on load with lasted AE2

### ISSUE THREAD

**Issue by Oxosorrel** [Chisel-2/Chisel-2#332]
Updated AE2 to latest release appliedenergistics2-rv2-stable-8, looks like they changed their quartz and skystone in  stable 7.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1588

Here is a partial crash log, if you need more let me know:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/14/15 3:32 PM
Description: Initializing game

java.lang.NullPointerException: Cannot add variation in group AECertusQuartz for null block.
	at com.cricketcraft.chisel.carving.Carving.addVariation(Carving.java:152)
	at com.cricketcraft.chisel.Features$1.addBlocks(Features.java:48)
	at com.cricketcraft.chisel.Features.loadBlocks(Features.java:2845)
	at com.cricketcraft.chisel.Features.preInit(Features.java:2914)
	at com.cricketcraft.chisel.Chisel.preInit(Chisel.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ate0ate** [comment]
I'm not getting any crashes using stable 9 of AE2 and the latest 2.4.0 dev build of chisel, however, I do notice that none of the chisel variants for AE2 blocks are available any longer.

**Comment by TheCricket** [comment]
This is absolutely their fault

**Comment by tterrag1098** [comment]
Agree with @ate0ate this works fine with stable 9. Undoing above commit, as it actually breaks it.
