### ISSUE TITLE
Chisel2 Freaking out.

### ISSUE THREAD

**Issue by Beelzaboss** [Chisel-2/Chisel-2#333]
Recently build a new modpack will the latest mods, And the latest AE2. When I open my GUI and put in Stone I crash and if I right click on stone it changes it into a Quantim Ring block. Why? I found also that in Magic Biomes (Thaumcraft) it generated Quantim Rings, but when I disabled the mossy feature from Chisel it suddenly stop generating Quantim Rings and Cobble.

Here is my log: 

[17:49:32] [Client thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockCarvableWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[17:49:32] [Client thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[17:49:32] [Client thread/WARN] [FML]: Unable to lookup chisel:voidstonerunic for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.voidstonerunic. Is there something wrong with the registry?
[17:49:32] [Client thread/WARN] [FML]: Unable to lookup chisel:circuits for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.circuits. Is there something wrong with the registry?
[17:49:32] [Client thread/WARN] [FML]: Unable to lookup chisel:bloodRune for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[17:49:32] [Client thread/WARN] [FML]: Unable to lookup chisel:bloodBrick for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[17:49:32] [Client thread/WARN] [FML]: Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?
[17:49:32] [Client thread/INFO] [FML]: Holder lookups applied
[17:49:36] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering item
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1391) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_05]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0_05]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_94608_d(Unknown Source) ~[add.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563) ~[bny.class:?]
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489) ~[GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270) ~[bex.class:?]
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_146977_a(GuiChisel.java:143) ~[GuiChisel.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99) ~[bex.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357) ~[blt.class:?]
	... 9 more
[17:49:37] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:-1]: ---- Minecraft Crash Report ----
// Don't do that.

Time: 18/6/15 5:49 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.item.ItemStack.func_94608_d(Unknown Source)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_146977_a(GuiChisel.java:143)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_94608_d(Unknown Source)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:161)

-- Item being rendered --
Details:
	Item Type: null
	Item Aux: ~~ERROR~~ NullPointerException: null
	Item NBT: null
	Item Foil: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_146977_a(GuiChisel.java:143)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)

-- Screen render details --
Details:
	Screen name: com.cricketcraft.chisel.client.gui.GuiChisel
	Mouse location: Scaled: (243, 105). Absolute: (487, 494)
	Screen size: Scaled: (680, 353). Absolute: (1360, 706). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['WineGumSniffer'/76, l='MpServer', x=839.91, y=68.62, z=3829.02]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-68,64,124), Chunk: (at 12,4,12 in -5,7; contains blocks -80,0,112 to -65,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1614392 game time, 1746256 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 26 total; [EntityMotherVoidwalker['Mother Void Walker'/2204, l='MpServer', x=-459.50, y=-0.03, z=1024.50], EntitySkellox['Skellox'/2446, l='MpServer', x=880.34, y=67.00, z=3883.50], EntityClown['Clown'/2205, l='MpServer', x=-461.50, y=-0.03, z=1021.50], EntitySkellox['Skellox'/2445, l='MpServer', x=884.50, y=67.00, z=3879.31], EntitySkellox['Skellox'/2444, l='MpServer', x=888.53, y=67.00, z=3866.22], EntityClientPlayerMP['WineGumSniffer'/76, l='MpServer', x=839.30, y=68.62, z=3830.70], EntitySandGolem['Sand Golem'/2601, l='MpServer', x=790.50, y=68.00, z=3850.50], EntitySpider['Spider'/8401, l='MpServer', x=14.90, y=-41.66, z=35.30], EntitySpider['Spider'/1601, l='MpServer', x=-27.55, y=-219.46, z=-18.50], EntitySphinx['Sphinx'/2218, l='MpServer', x=-439.50, y=39.07, z=1074.50], EntityVoidwalker['Void Walker'/1271, l='MpServer', x=184.50, y=-0.02, z=2253.50], EntityWickett['Wickett'/2217, l='MpServer', x=801.84, y=63.00, z=3794.31], EntityKeese['Keese'/2081, l='MpServer', x=133.50, y=17.10, z=2225.50], EntityTricksterClone['Trickster'/1518, l='MpServer', x=164.56, y=-0.02, z=2272.69], EntityWickett['Wickett'/2214, l='MpServer', x=800.94, y=63.00, z=3796.59], EntityZombie['Zombie'/2212, l='MpServer', x=807.50, y=63.00, z=3795.50], EntityCreeper['Creeper'/2143, l='MpServer', x=794.50, y=63.00, z=3809.50], EntityClientPlayerMP['WineGumSniffer'/76, l='MpServer', x=839.91, y=68.62, z=3829.02], EntitySkellox['Skellox'/2795, l='MpServer', x=797.50, y=76.00, z=3864.50], EntitySkeleton['Skeleton'/6997, l='MpServer', x=3.79, y=-0.01, z=-23.61], EntityNightReaper['Night Reaper'/2785, l='MpServer', x=888.50, y=68.00, z=3877.50], EntityNightReaper['Night Reaper'/2784, l='MpServer', x=891.50, y=68.00, z=3879.50], EntityItem['item.item.dyePowder.black'/1669, l='MpServer', x=871.44, y=36.13, z=3783.03], EntitySpider['Spider'/1339, l='MpServer', x=13.07, y=-200.88, z=34.94], EntityNightReaper['Night Reaper'/2783, l='MpServer', x=890.50, y=68.00, z=3874.50], EntityVoidwalker['Void Walker'/2558, l='MpServer', x=808.50, y=30.00, z=3844.50]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976892008 bytes (931 MB) / 1976369152 bytes (1884 MB) up to 1976369152 bytes (1884 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -Xms256M -Xmx2048M -XX:MaxPermSize=250M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95

**Comment by CptSpaceToaster** [comment]
Give it a blanket, it's favorite stuffed animal, and a couple of minutes

**Comment by CptSpaceToaster** [comment]
Related: https://github.com/Chisel-2/Chisel-2/issues/332

**Comment by CptSpaceToaster** [comment]
The stone crash might be a stone variant that's not registred in the oredict? https://github.com/SleepyTrousers/EnderIO/issues/2579

The Thaumcraft config issue sounds absolutely bonkers... taking a quick look
