### ISSUE TITLE
Crash with Chisel "ClassCastException"

### ISSUE THREAD

**Issue by SanAndreasP** [Chisel-2/Chisel-2#395]
Minecraft 1.7.10
Forge 10.13.4.1451
Chisel 2.5.0.161 (DEV) / Chisel 2.5.0-42

Problem:
I recently tried to chisel white stained glass, only to encounter this crash:
```
java.lang.ClassCastException: com.cricketcraft.chisel.block.BlockCarvableGlass cannot be cast to com.cricketcraft.chisel.block.BlockCarvable
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_73876_c(GuiChisel.java:82)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Now I can't even open the GUI without crashing, making the chisel and its content unusable. Now I suspect a mod compatibility issue with some mod.
What would be nice is blocks affecting this simply not showing up in the GUI, or at the very least, try to print out the offending class name so it would be easier to see which mod causes this error.

Here are the complete logs:
https://gist.github.com/SanAndreasP/b7f674a3a4f46d0425b5

**Comment by Nortervolter** [comment]
I am having the same problem with identical log in my gave when I tried to convert glass to quite clear glass for ender io

**Comment by ANNOYEDCHERRY** [comment]
Having the same issue myself. I tested it with other blocks, looks like its just limited to glass in general. I also tested left clicking the glass block, that works fine (only recommend doing that if you have an obsidian chisel or diamond chisel (more durability)).

**Comment by erindalc** [comment]
I can also confirm this bug, I wasn't even doing anything involving glass when it happened.

**Comment by TheCricket** [comment]
Yep I am fixing it now

**Comment by ANNOYEDCHERRY** [comment]
Until next update with the patch I recommend using version 2.4.1

**Comment by TheCricket** [comment]
Hotfix in place

**Comment by SanAndreasP** [comment]
Cool, thanks! :baby_chick:

**Comment by SanAndreasP** [comment]
I can confirm it's working now!  :+1:
