### ISSUE TITLE
Sandstone cannot be cast to BlockCarvable

### ISSUE THREAD

**Issue by Skipachu** [Chisel-2/Chisel-2#405]
forge-1.7.10-10.13.4.1492-1.7.10-universal.jar
Chisel2-2.5.0.42

When Shift-clicking a stack of sandstone into the chisel's GUI, local client crashed. Logging back into the game, the chisel shows sandstone icon in the corner indicating it is holding the stack. When I right-click to re-open the GUI, Client crashes. Here is the error given:
Time: 8/31/15 4:52 PM
Description: Ticking screen

java.lang.ClassCastException: com.cricketcraft.chisel.block.BlockSnakestone cannot be cast to com.cricketcraft.chisel.block.BlockCarvable
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_73876_c(GuiChisel.java:82)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- Head --
Stacktrace:
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_73876_c(GuiChisel.java:82)

-- Affected screen --
Details:
	Screen name: com.cricketcraft.chisel.client.gui.GuiChisel

**Comment by TheCricket** [comment]
Update
